apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    avp.kubernetes.io/path: "secret/data/test"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env:
      - name: TEST_SECRET
        value: <test_val>
